### PR TITLE
Bump six version, because of failing celery

### PR DESCRIPTION
**Pull request by lc0**
Hello folks, 

My Python version is **2.7.10**

seems like there are some issues with Celery dependency:

```
Collecting snowplow-analytics-sdk==0.1.0
  Downloading snowplow_analytics_sdk-0.1.0.tar.gz
Installing collected packages: snowplow-analytics-sdk
  Running setup.py install for snowplow-analytics-sdk ... - done
Successfully installed snowplow-analytics-sdk-0.1.0
Requirement already satisfied: boto3==1.4.1 in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages
Requirement already satisfied: botocore<1.5.0,>=1.4.1 in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from boto3==1.4.1)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.0 in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from boto3==1.4.1)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from boto3==1.4.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from botocore<1.5.0,>=1.4.1->boto3==1.4.1)
Requirement already satisfied: docutils>=0.10 in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from botocore<1.5.0,>=1.4.1->boto3==1.4.1)
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from s3transfer<0.2.0,>=0.1.0->boto3==1.4.1)
Requirement already satisfied: six>=1.5 in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.5.0,>=1.4.1->boto3==1.4.1)
Requirement already satisfied: PyYAML==3.12 in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages
Collecting snowplow-tracker==0.8.0
  Downloading snowplow-tracker-0.8.0.tar.gz
Collecting greenlet==0.4.10 (from snowplow-tracker==0.8.0)
  Downloading greenlet-0.4.10-cp27-cp27m-manylinux1_x86_64.whl (41kB)
    100% |████████████████████████████████| 51kB 9.3MB/s 
Collecting requests==2.2.1 (from snowplow-tracker==0.8.0)
  Downloading requests-2.2.1-py2.py3-none-any.whl (625kB)
    100% |████████████████████████████████| 634kB 1.9MB/s 
Collecting pycontracts==1.7.6 (from snowplow-tracker==0.8.0)
  Downloading PyContracts-1.7.6.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 8.5MB/s 
Collecting celery==3.1.11 (from snowplow-tracker==0.8.0)
  Downloading celery-3.1.11-py27-none-any.whl (513kB)
    100% |████████████████████████████████| 522kB 2.2MB/s 
Collecting gevent==1.0.2 (from snowplow-tracker==0.8.0)
  Downloading gevent-1.0.2.tar.gz (1.7MB)
    100% |████████████████████████████████| 1.7MB 768kB/s 
Collecting redis==2.9.1 (from snowplow-tracker==0.8.0)
  Downloading redis-2.9.1.tar.gz (62kB)
    100% |████████████████████████████████| 71kB 10.2MB/s 
Collecting six==1.9.0 (from snowplow-tracker==0.8.0)
  Downloading six-1.9.0-py2.py3-none-any.whl
Requirement already satisfied: pyparsing in /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (from pycontracts==1.7.6->snowplow-tracker==0.8.0)
Collecting decorator (from pycontracts==1.7.6->snowplow-tracker==0.8.0)
  Downloading decorator-4.0.11-py2.py3-none-any.whl
Collecting kombu<4.0,>=3.0.15 (from celery==3.1.11->snowplow-tracker==0.8.0)
  Downloading kombu-3.0.37-py2.py3-none-any.whl (240kB)
    100% |████████████████████████████████| 245kB 4.4MB/s 
Collecting billiard<3.4,>=3.3.0.17 (from celery==3.1.11->snowplow-tracker==0.8.0)
  Downloading billiard-3.3.0.23.tar.gz (151kB)
    100% |████████████████████████████████| 153kB 6.0MB/s 
Collecting pytz>dev (from celery==3.1.11->snowplow-tracker==0.8.0)
  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)
    100% |████████████████████████████████| 491kB 2.7MB/s 
Collecting anyjson>=0.3.3 (from kombu<4.0,>=3.0.15->celery==3.1.11->snowplow-tracker==0.8.0)
  Downloading anyjson-0.3.3.tar.gz
Collecting amqp<2.0,>=1.4.9 (from kombu<4.0,>=3.0.15->celery==3.1.11->snowplow-tracker==0.8.0)
  Downloading amqp-1.4.9-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 61kB 10.1MB/s 
Installing collected packages: greenlet, requests, decorator, six, pycontracts, anyjson, amqp, kombu, billiard, pytz, celery, gevent, redis, snowplow-tracker
  Found existing installation: requests 2.12.5
    Uninstalling requests-2.12.5:
      Successfully uninstalled requests-2.12.5
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Running setup.py install for pycontracts ... - error
    Complete output from command /home/ubuntu/virtualenvs/venv-2.7.9/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hf0R7z/pycontracts/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aT935i-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/virtualenvs/venv-2.7.9/include/site/python2.7/pycontracts:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hf0R7z/pycontracts/setup.py", line 53, in <module>
        entry_points={},
      File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2306, in require
        items = working_set.resolve(reqs, env, installer)
      File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.9.0 (/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages), Requirement.parse('six>=1.10.0'))
    
    ----------------------------------------
Command "/home/ubuntu/virtualenvs/venv-2.7.9/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hf0R7z/pycontracts/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aT935i-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/virtualenvs/venv-2.7.9/include/site/python2.7/pycontracts" failed with error code 1 in /tmp/pip-build-hf0R7z/pycontracts/
```

In particular with 
```
pkg_resources.VersionConflict: (six 1.9.0 (/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages), Requirement.parse('six>=1.10.0'))
```

It works fine if one bumps version of six to **1.10.0**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify. Thanks.

**Comment by lc0** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @lc0 has signed the Individual Contributor License Agreement. Thanks so much

**Comment by mhadam** [comment]
closing this in favor of #209

**Pull request closed without merging**
