### PR TITLE
Add Python 3.12 to CI tests (close #356)

### LINKED ISSUE #356: Add Python 3.12 to CI tests
Python 3.12 was released recently. We should make sure it works with the tracker and add it to the list of tested Python versions [in CI here](https://github.com/snowplow/snowplow-python-tracker/blob/master/.github/workflows/ci.yml#L15).

### PR DESCRIPTION
**Pull request by edgarrmondragon**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by edgarrmondragon** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @edgarrmondragon has signed the Contributor License Agreement. Thanks so much.

**Comment by Jack-Keene** [comment]
Hi @edgarrmondragon, thanks for making a contribution to the Snowplow Python Tracker!

There's a couple of changes required before we add can add this to a release, namely adding the new version to the tests and the Dockerfile. See [this PR](https://github.com/snowplow/snowplow-python-tracker/pull/287) for adding support to Python 3.11 for an example.

**Comment by edgarrmondragon** [comment]
> Hi @edgarrmondragon, thanks for making a contribution to the Snowplow Python Tracker!
> 
> There's a couple of changes required before we add can add this to a release, namely adding the new version to the tests and the Dockerfile. See [this PR](https://github.com/snowplow/snowplow-python-tracker/pull/287) for adding support to Python 3.11 for an example.

Thanks for the pointer @Jack-Keene! I've added 3.12 where it was missing.

**Review by Jack-Keene — APPROVED** [review]
LGTM!

**Pull request merged**
