### PR TITLE
Configurable timeouts for emitter http requests

### PR DESCRIPTION
**Pull request by DeyanDeyanov**
The PR addresses this issue: https://github.com/snowplow/snowplow-python-tracker/issues/258

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by DeyanDeyanov** [comment]
I signed it

**Comment by paulboocock** [comment]
Thanks for signing the CLA. Once I have more clarity on when we'll get the next python tracker update out, I'll give you an update.

**Review by matus-tomlein — APPROVED** [review]
Thank you for the contribution, @DeyanDeyanov! I [cherry-picked your commit](https://github.com/snowplow/snowplow-python-tracker/commit/6f57578ffb3d3a9368dc666b6df8348716db358c) to be published in the upcoming 0.10.0 release.

**Comment by matus-tomlein** [comment]
Cherry-picked into the 0.10.0 release branch.

**Pull request closed without merging**
