### PR TITLE
Update README file (close #264)

### LINKED ISSUE #264: Update README file
Change the quick start guide to use Docker instead of Pyenv

### PR DESCRIPTION
**Pull request by Jack-Keene**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Review by AlexBenny — CHANGES_REQUESTED** [review]
Great, thanks for fixing these old README.
I'm adding here a comment for things we have already discussed in our meeting:
- convert this README.rst file to README.md (like the other trackers)
- update the copyright note in the bottom
- update this PR (and the other ones) against a new "release/0.11" branch rather than "master"

**Comment by paulboocock** [comment]
Does renaming to .md from .rst have any detrimental effects on the PyPi page?

**Comment by AlexBenny** [comment]
> Does renaming to .md from .rst have any detrimental effects on the PyPi page?

I think it shouldn't, [their page](https://github.com/pypa/readme_renderer) says
> It can handle Markdown, reStructuredText (.rst), and plain text.

**Review by AlexBenny — APPROVED** [review]
LGTM!

**Pull request merged**
