### PR TITLE
Test with Python 3.13

### PR DESCRIPTION
**Pull request by edgarrmondragon**

### CODE REVIEW

**Comment by miike** [comment]
My feeling is that we probably hold off on this until early October so we're running tests against 3.13 stable rather than one of the 3.13 release candidates.

**Comment by edgarrmondragon** [comment]
> My feeling is that we probably hold off on this until early October so we're running tests against 3.13 stable rather than one of the 3.13 release candidates.

Happy to keep this open and come back around October 1st to make the changes for the final release.

**Comment by miike** [comment]
Thanks @edgarrmondragon, much appreciated. I'll set up a reminder as well.

**Comment by miike** [comment]
It's October 1st but the final release of 3.13 has been pushed out to the 7th, will check back in then.

**Comment by edgarrmondragon** [comment]
I'm opening this for review, although this hasn't been released yet:

- https://github.com/pyenv/pyenv/pull/3081

**Comment by edgarrmondragon** [comment]
ping @miike 🙏

**Review by matus-tomlein — APPROVED** [review]
Thanks for the contribution @edgarrmondragon and sorry for the delay! We will take it from here.

**Pull request merged**
