### PR TITLE
Allow empty strings in string_or_none contract

### PR DESCRIPTION
**Pull request by joshblum**
Addresses #184

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by joshblum** [comment]
Signed :)

**Comment by snowplowcla** [comment]
Confirmed! @joshblum has signed the Individual Contributor License Agreement. Thanks so much

**Comment by joshblum** [comment]
@chuwy How does this look to address #184 ??

**Comment by joshblum** [comment]
@chuwy any update?

**Comment by chuwy** [comment]
Hey @joshblum! Sure, this looks fine. I milestoned corresponding issue with closest release, it'll be included.

**Comment by joshblum** [comment]
Awesome thanks :)

**Comment by oguzhanunlu** [comment]
Thanks for the contribution @joshblum ! It is cherry-picked to the release branch at #224 .

**Pull request closed without merging**
