### PR TITLE
Update requirement: redis-py 3

### PR DESCRIPTION
**Pull request by akachanov**
Looks like code is compatible with redis-py 3
https://github.com/andymccurdy/redis-py#upgrading-from-redis-py-2x-to-30

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by akachanov** [comment]
I signed it

**Comment by snowplowcla** [comment]
Confirmed! @akachanov  has signed the Individual Contributor License Agreement. Thanks so much

**Comment by oguzhanunlu** [comment]
Thanks for the contribution @akachanov ! It is cherry-picked to the release branch at #224 .

**Pull request closed without merging**
