### PR TITLE
Add Python 3.11 to CI tests (close #286)

### LINKED ISSUE #286: Add Python 3.11 to CI tests
Python 3.11 was [released recently](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291). We should make sure it works with the tracker and add it to the list of tested Python versions [in CI here](https://github.com/snowplow/snowplow-python-tracker/blob/master/.github/workflows/ci.yml#L15).

### PR DESCRIPTION
**Pull request by Jack-Keene**
This PR adds Python 3.11.0 to the CI tests

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Review by matus-tomlein — APPROVED** [review]
LGTM! 👍

**Comment by matus-tomlein** [comment]
Just realized one more thing – could you add Python 3.11 to the list of tags in the [setup.py file here](https://github.com/snowplow/snowplow-python-tracker/blob/master/setup.py#L65)? It would make it show among the supported Python versions in README.

**Comment by Jack-Keene** [comment]
Done 👍

**Pull request merged**
