### PR TITLE
Add additional supported platforms to Subject

### PR DESCRIPTION
**Pull request by miike**
Adds additional platforms ("web", "srv", "app") to the Subject contract.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @miike - can you sign our CLA please? https://github.com/snowplow/snowplow/wiki/CLA

**Comment by miike** [comment]
Sure, should be signed up on both now.

**Comment by alexanderdean** [comment]
Confirmed - thanks @miike !

**Comment by chuwy** [comment]
It was cherry-picked. Closing PR in favor of issue: #172. Thanks

**Pull request closed without merging**
