### PR TITLE
Initializes Celery app in CeleryEmitter.

### LINKED ISSUE #185: Emitter: Don't initialize Celery app on module import
I'm adding your snowplow-python-tracker to my django app right now. Currently I'm running into an issue whenever I import the Emitter class. Looking at your code, you guys seem to do some stuff to create a Celery app in the main body of the Emitter module. The problem in my current case is that this code gets executed before my logic to create the default celery app for my django project. As a result, the default celery app get's set to Snowplow and celery stops working for my app. Seems to me this logic should be set in `__init__` of the `CeleryEmitter` instead. There's plenty of ways for me to work around this for now, but I thought you guys should be aware of this. It took me a while to identify this as the central cause, and may trip up others in similar situations. I'm happy to throw up a fix, if you guys would like that.

### PR DESCRIPTION
**Pull request by juliomenendez**
Fixes #185

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by juliomenendez** [comment]
I signed it!

**Comment by juliomenendez** [comment]
Thanks! What should I do about the tests failing for Python 3.3? Remove that version entirely maybe?

**Comment by chuwy** [comment]
Good question. For me Python 3.3 doesn't look outdated yet. Let's wait until we have a bandwidth for a new release and we'll decide what to do with 3.3 then.

Also, it looks like problem not in tracker, but in other our project - [release-manager](https://github.com/snowplow/release-manager/), which is a bit suspicious. Maybe we can stick with earlier version (e.g. 0.2.0)

**Comment by oguzhanunlu** [comment]
Hi @juliomenendez , thanks for the contribution! It is cherry-picked to the release branch at #224 .

**Pull request closed without merging**
