### PR TITLE
Added client support of `tnx_id` field

### PR DESCRIPTION
**Pull request by xen**
Hi,
I added support to python client library for `tnx_id` field which is described as canonical field, but wasn't implemented in client library.

Also, I fixed some documentation indentation issues.

### CODE REVIEW

**Comment by fblundun** [comment]
Hi @xen ,

The Python Tracker used to support the `txn_id` field. It was a random 6-digit number attached to each event, used for deduplication. You can see the implementation in the first version of the Python Tracker [here](https://github.com/snowplow/snowplow-python-tracker/blob/0.1.0/snowplow_tracker/payload.py#L39).

We decided that with only 6 digits, the risk of two events having the same `txn_id` was still too high. For this reason, we have deprecated this field and we are replacing it with an "event ID" in all our trackers. The event ID is a version 4 UUID, making collisions much less likely. [Here](https://github.com/snowplow/snowplow-python-tracker/blob/master/snowplow_tracker/tracker.py#L145) is where we add it in the latest Python Tracker version.

I have altered our documentation to make it clear that the `txn_id` field is deprecated - sorry for the confusion!

**Comment by xen** [comment]
Well, this makes things little more different for us. Since we plan to use this param as identifier of "active window session id" along with network user id. We will stick with event_id for now. Thank you for clarification.

**Comment by alexanderdean** [comment]
Closing this PR...

**Comment by xen** [comment]
Sure.

**Pull request closed without merging**
